name: Deploy to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 push할 때 실행 ~

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" | sed 's/\r$//' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 15.164.213.127 >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@15.164.213.127 << 'EOF'

            echo "Changing ownership of the repository..."
            sudo chown -R ubuntu:ubuntu /usr/share/nginx/react-mbti
            echo "cd /usr/share/nginx/react-mbti"
            cd /usr/share/nginx/react-mbti
            # git config --global --add safe.directory /usr/share/nginx/react-mbti
            echo "git pull origin main"
            git pull origin main
            echo "npm install"
            npm install
            echo "npm run build"
            npm run build
            
            echo "pm2 restart react-app"
            pm2 restart react-app || pm2 start npm --name "react-app" -- start
            
            # Nginx 재시작
            echo "systemctl restart nginx"
            sudo systemctl restart nginx
          EOF
