name: Deploy to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 push할 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          printf "%s" "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          touch ~/.ssh/known_hosts
          ssh-keyscan -H 15.164.213.127 >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@15.164.213.127 << 'EOF'
            cd /usr/share/nginx/react-mbti
            git pull origin main
            npm install
            npm run build
            
            # PM2를 사용하여 React 앱 실행
            # pm2 delete react-app || true
            # pm2 start npm --name "react-app" -- start
            # pm2 save
            
            # Nginx 재시작
            sudo systemctl restart nginx
          EOF
